<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-6QB5I7N" failures="1" tests="4" name="PetStoreTest" time="5.18" errors="0" timestamp="2025-04-03T22:08:11 IST">
  <testcase classname="api.test.UserTest2" name="postTestCreateUser" time="3.125"/>
  <testcase classname="api.test.UserTest2" name="getTestUserByName" time="1.109">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTest2.getTestUserByName(UserTest2.java:57)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- getTestUserByName -->
  <testcase classname="api.test.UserTest2" name="putTestUpdateUserByName" time="0.0">
    <skipped/>
  </testcase> <!-- putTestUpdateUserByName -->
  <testcase classname="api.test.UserTest2" name="deleteTestUserByName" time="0.0">
    <skipped/>
  </testcase> <!-- deleteTestUserByName -->
</testsuite> <!-- PetStoreTest -->
